name: Homepage

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm run build --if-present

      # cleanup
      - run: rm -rf docs

      # storybook
      - run: npm run storybook:build

      # typedoc
      - run: npm run typedoc

      # homepage
      - run: npm ci
        working-directory: homepage
      - run: npm run build:gh
        working-directory: homepage
      - name: Github Pages
        uses: crazy-max/ghaction-github-pages@v1.2.5
        with:
          build_dir: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
